=begin
#Ilinaya SMSFlow

#Ilinaya SMSFlow API

OpenAPI spec version: 1.0.0
Contact: all@ilinaya.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'uri'

module SwaggerClient
  class AuthorizeApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Get BEARER token
    # Obtain token for API call. Token must be sent in every request in Authorization: Bearer <xxx> header, where <xxx> is your token. You may decode token to get token expiration. We use standard JWT
    # @param body Username and password must be sent via json object
    # @param [Hash] opts the optional parameters
    # @return [TokenResponse]
    def authorize_post(body, opts = {})
      data, _status_code, _headers = authorize_post_with_http_info(body, opts)
      data
    end

    # Get BEARER token
    # Obtain token for API call. Token must be sent in every request in Authorization: Bearer &lt;xxx&gt; header, where &lt;xxx&gt; is your token. You may decode token to get token expiration. We use standard JWT
    # @param body Username and password must be sent via json object
    # @param [Hash] opts the optional parameters
    # @return [Array<(TokenResponse, Fixnum, Hash)>] TokenResponse data, response status code and response headers
    def authorize_post_with_http_info(body, opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: AuthorizeApi.authorize_post ...'
      end
      # verify the required parameter 'body' is set
      if @api_client.config.client_side_validation && body.nil?
        fail ArgumentError, "Missing the required parameter 'body' when calling AuthorizeApi.authorize_post"
      end
      # resource path
      local_var_path = '/authorize'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = @api_client.object_to_http_body(body)
      auth_names = []
      data, status_code, headers = @api_client.call_api(:POST, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'TokenResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: AuthorizeApi#authorize_post\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
