=begin
#Ilinaya SMSFlow

#Ilinaya SMSFlow API

OpenAPI spec version: 1.0.0
Contact: all@ilinaya.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'uri'

module SwaggerClient
  class UsersApi
    attr_accessor :api_client

    def initialize(api_client = ApiClient.default)
      @api_client = api_client
    end
    # Retrieve financial information
    # Get available balance and credits
    # @param [Hash] opts the optional parameters
    # @return [BalanceResponse]
    def users_balance_get(opts = {})
      data, _status_code, _headers = users_balance_get_with_http_info(opts)
      data
    end

    # Retrieve financial information
    # Get available balance and credits
    # @param [Hash] opts the optional parameters
    # @return [Array<(BalanceResponse, Fixnum, Hash)>] BalanceResponse data, response status code and response headers
    def users_balance_get_with_http_info(opts = {})
      if @api_client.config.debugging
        @api_client.config.logger.debug 'Calling API: UsersApi.users_balance_get ...'
      end
      # resource path
      local_var_path = '/users/balance'

      # query parameters
      query_params = {}

      # header parameters
      header_params = {}
      # HTTP header 'Accept' (if needed)
      header_params['Accept'] = @api_client.select_header_accept(['application/json'])
      # HTTP header 'Content-Type'
      header_params['Content-Type'] = @api_client.select_header_content_type(['application/json'])

      # form parameters
      form_params = {}

      # http body (model)
      post_body = nil
      auth_names = ['apiKey']
      data, status_code, headers = @api_client.call_api(:GET, local_var_path,
        :header_params => header_params,
        :query_params => query_params,
        :form_params => form_params,
        :body => post_body,
        :auth_names => auth_names,
        :return_type => 'BalanceResponse')
      if @api_client.config.debugging
        @api_client.config.logger.debug "API called: UsersApi#users_balance_get\nData: #{data.inspect}\nStatus code: #{status_code}\nHeaders: #{headers}"
      end
      return data, status_code, headers
    end
  end
end
