=begin
#Ilinaya SMSFlow

#Ilinaya SMSFlow API

OpenAPI spec version: 1.0.0
Contact: all@ilinaya.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::CallerIdsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'CallerIdsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::CallerIdsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of CallerIdsApi' do
    it 'should create an instance of CallerIdsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::CallerIdsApi)
    end
  end

  # unit tests for caller_ids_get
  # Retrieve your caller IDs
  # Get available caller IDs, you may add them, but 2FA confirmation is required for every new callerId. 
  # @param [Hash] opts the optional parameters
  # @return [CallerIdsResponse]
  describe 'caller_ids_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
