=begin
#Ilinaya SMSFlow

#Ilinaya SMSFlow API

OpenAPI spec version: 1.0.0
Contact: all@ilinaya.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::MessagesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'MessagesApi' do
  before do
    # run before each test
    @instance = SwaggerClient::MessagesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of MessagesApi' do
    it 'should create an instance of MessagesApi' do
      expect(@instance).to be_instance_of(SwaggerClient::MessagesApi)
    end
  end

  # unit tests for messages_get
  # Retrieve sent and recieved messages
  # This method allows you to get paginated output of your messages
  # @param [Hash] opts the optional parameters
  # @option opts [Float] :page Specify Page number for results pagination
  # @return [MessagesResponse]
  describe 'messages_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for messages_send_post
  # Send Messages
  # Method allows you to send text message to one or many destination numbers
  # @param body order placed for purchasing the pet
  # @param [Hash] opts the optional parameters
  # @return [MessageSendResponse]
  describe 'messages_send_post test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for messages_status_message_id_get
  # Retrieve message
  # This method allows you to get information about specific message
  # @param message_id Numeric ID of the user to get
  # @param [Hash] opts the optional parameters
  # @return [MessageStatusResponse]
  describe 'messages_status_message_id_get test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
