=begin
#Ilinaya SMSFlow

#Ilinaya SMSFlow API

OpenAPI spec version: 1.0.0
Contact: all@ilinaya.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::DidSetCallbackRequest
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'DidSetCallbackRequest' do
  before do
    # run before each test
    @instance = SwaggerClient::DidSetCallbackRequest.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of DidSetCallbackRequest' do
    it 'should create an instance of DidSetCallbackRequest' do
      expect(@instance).to be_instance_of(SwaggerClient::DidSetCallbackRequest)
    end
  end
  describe 'test attribute "did_id"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "did_callback_url"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
