=begin
#Ilinaya SMSFlow

#Ilinaya SMSFlow API

OpenAPI spec version: 1.0.0
Contact: all@ilinaya.com
Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.13

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/availavble_caller_id_item'
require 'swagger_client/models/availavble_did_item'
require 'swagger_client/models/availavle_did_response'
require 'swagger_client/models/balance_response'
require 'swagger_client/models/caller_ids_response'
require 'swagger_client/models/did'
require 'swagger_client/models/did_did'
require 'swagger_client/models/did_purchase_request'
require 'swagger_client/models/did_purchase_response'
require 'swagger_client/models/did_purchase_response_did'
require 'swagger_client/models/did_response'
require 'swagger_client/models/did_response_info'
require 'swagger_client/models/did_set_callback_request'
require 'swagger_client/models/did_set_callback_response'
require 'swagger_client/models/message'
require 'swagger_client/models/message_send_request'
require 'swagger_client/models/message_send_response'
require 'swagger_client/models/message_send_response_message_item'
require 'swagger_client/models/message_status_response'
require 'swagger_client/models/messages_response'
require 'swagger_client/models/package'
require 'swagger_client/models/package_purchase_history_response'
require 'swagger_client/models/package_purchase_request'
require 'swagger_client/models/package_purchase_response'
require 'swagger_client/models/packages_response'
require 'swagger_client/models/purchase_history_item'
require 'swagger_client/models/purchase_history_item_did'
require 'swagger_client/models/purchase_history_item_organization_user'
require 'swagger_client/models/purchase_history_item_package'
require 'swagger_client/models/token_request'
require 'swagger_client/models/token_response'
require 'swagger_client/models/user'

# APIs
require 'swagger_client/api/authorize_api'
require 'swagger_client/api/caller_ids_api'
require 'swagger_client/api/dids_api'
require 'swagger_client/api/messages_api'
require 'swagger_client/api/packages_api'
require 'swagger_client/api/users_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
